TryAtSoftware/Extensions

- TryAtSoftware.Extensions.Reflection.Tests/ExpressionsExtensionsTests.cs
- TryAtSoftware.Extensions.Reflection.Tests/MembersBinderExtensionsTests.cs
- TryAtSoftware.Extensions.Reflection.Tests/MembersBinderTests.cs
- TryAtSoftware.Extensions.Reflection.Tests/Models/Person.cs
- TryAtSoftware.Extensions.Reflection.Tests/Models/Specialized/ModelWithInaccessibleProperty.cs
- TryAtSoftware.Extensions.Reflection.Tests/Models/Student.cs
- TryAtSoftware.Extensions.Reflection.Tests/Randomization/PersonRandomizer.cs
- TryAtSoftware.Extensions.Reflection.Tests/TypeNamesTests.cs
- TryAtSoftware.Extensions.Reflection.Tests/Types/Person.cs
- TryAtSoftware.Extensions.Reflection/ExpressionsExtensions.cs
This PR also includes test improvements
> Added an extension method for constructing an expression for setting the value of a property

- README.md
- TryAtSoftware.Extensions.Collections.Tests/CollectionExtensionsTests.cs
- TryAtSoftware.Extensions.Collections/CollectionExtensions.cs
- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
- TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
It should be called `Union` instead.
> Fixed the name of the `SetIntersection` extension method

- TryAtSoftware.Extensions.Reflection.Benchmark/BenchmarkModel.cs
- TryAtSoftware.Extensions.Reflection.Benchmark/ModelInstantiating.cs
- TryAtSoftware.Extensions.Reflection.Benchmark/Program.cs
- TryAtSoftware.Extensions.Reflection.Benchmark/ReflectionVsExpressions.cs
- TryAtSoftware.Extensions.Reflection.Benchmark/TryAtSoftware.Extensions.Reflection.Benchmark.csproj
- TryAtSoftware.Extensions.Reflection.Benchmark/ValueRetrieving.cs
- TryAtSoftware.Extensions.Reflection.Benchmark/ValueSetting.cs
- TryAtSoftware.Extensions.sln
Added benchmark tests for the following operations:
- Retrieve the value of a property
- Set a value to a property
- Create a new instance of a model
> Benchmark `TryAtSoftware.Extensions.Reflection`

- TryAtSoftware.Extensions.Collections/CollectionExtensions.cs
- TryAtSoftware.Extensions.Reflection.Tests/HierarchyScannerTests.cs
- TryAtSoftware.Extensions.Reflection.md
- TryAtSoftware.Extensions.Reflection/HierarchyScanner.cs
- TryAtSoftware.Extensions.Reflection/Interfaces/IHierarchyScanner.cs
> Introducing the `IHierarchyScanner` component

- TryAtSoftware.Extensions.Collections.Tests/TryAtSoftware.Extensions.Collections.Tests.csproj
- TryAtSoftware.Extensions.Collections.md
- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
- TryAtSoftware.Extensions.Reflection.Tests/Randomization/AgeRandomizer.cs
- TryAtSoftware.Extensions.Reflection.Tests/Randomization/PersonRandomizer.cs
- TryAtSoftware.Extensions.Reflection.Tests/Randomization/StudentRandomizer.cs
- TryAtSoftware.Extensions.Reflection.Tests/TryAtSoftware.Extensions.Reflection.Tests.csproj
- TryAtSoftware.Extensions.Reflection.md
- TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
Upgraded all development packages to latest and made improvements to the documentation of all libraries,
> Housekeeping

- TryAtSoftware.Extensions.Reflection.md
- TryAtSoftware.Extensions.Reflection/AssemblyExtensions.cs
- TryAtSoftware.Extensions.Reflection/Options/LoadReferencedAssembliesOptions.cs
Added documentation within the README,md file of the `TryAtSoftware.Extensions.Reflection` package for the new Assembly extensions.
> Added documentation for the new assembly extensions

- TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
This PR will introduce a new pre-release for the `TryAtSoftware.Extensions.Reflection` package.
> Increased the `TryAtSoftware.Extensions.Reflection` package version to 1.1.2-alpha.1

- .github/workflows/Core validation.yml
Renamed the workflow and the main job to `CI`.
Updated all actions to latest.
> Made improvements to the `Core validation` CI pipeline

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
Added a CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md, issue and pull request templates
> Applying recommended community standards

- TryAtSoftware.Extensions.Reflection.Tests/MemberInfoExtensionsTests.cs
- TryAtSoftware.Extensions.Reflection.Tests/TypeNamesTests.cs
There were some accumulated code smells due to changes in the analyzation executed by Sonar. This PR should fix all of them, resulting in 0 code smells for the project.
We want to deliver high quality solutions.
> Fixed code smells

- .github/workflows/Core validation.yml
This PR introduces significant changes to the way SonarCloud analyzes `TryAtSoftware.Extensions` as a part of the CI/CD process - the `GITHUB_TOKEN` secret is no longer used (we do not know if this could potentially introduce some issues along the way).
We want the main development team and the community members to have an equal validation and analyzation standard for the quality of their changes.
> Workflow optimizations for contributors (Uncertain changes)

- TryAtSoftware.Extensions.DependencyInjection.Standard.md
Fixed a mistake in the documentation of `TryAtSoftware.Extensions.DependencyInjection.Standart`
_[Explain in details the reasoning behind these changes and provide any relevant context. This can include potential impact or any alternative solutions considered.]_
> Fixed a mistake in the documentation of `TryAtSoftware.Extensions.DependencyInjection.Standart`

- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
> Increased the `TryAtSoftware.Extensions.Collections` package version to 1.1.2-alpha.1

- TryAtSoftware.Extensions.Collections.Tests/BitmaskTests.cs
- TryAtSoftware.Extensions.Collections.md
- TryAtSoftware.Extensions.Collections/Bitmask.cs
Introduced shift operators for the `Bitmask` class.
With these changes being implemented, the bitwise operations story will be completed.
> Shift operators for bitmask

- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
> Increased the `TryAtSoftware.Extensions.Collections` package version to 1.1.2-alpha.2

- TryAtSoftware.Extensions.Collections.Tests/BitmaskTests.cs
- TryAtSoftware.Extensions.Collections.md
- TryAtSoftware.Extensions.Collections/Bitmask.cs
- TryAtSoftware.Extensions.Collections/Internal/Bits.cs
Implemented the `FindMostSignificantSetBit` and `FindMostSignificantUnsetBit` methods.
The new methods should extend the existing pair of methods operating over the least significant bits.
> Find most significant set/unset bit

- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
> Increased the `TryAtSoftware.Extensions.Collections` package version to 1.1.2-alpha.3

- TryAtSoftware.Extensions.Collections.Tests/BitmaskTests.cs
- TryAtSoftware.Extensions.Collections.md
- TryAtSoftware.Extensions.Collections/Bitmask.cs
- TryAtSoftware.Extensions.Collections/Internal/Bits.cs
Implemented, documented and tested the new `CountSetBits` and `CountUnsetBits` methods for the `Bitmask` class.
We need a method to count the set/unset bits of a bitmask.
> Count set/unset bits

- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
> Increased the `TryAtSoftware.Extensions.Collections` package version to 1.1.2-alpha.4

- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
> Increased the `TryAtSoftware.Extensions.Collections` package version to 1.1.2-alpha.5

- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
> Increased the `TryAtSoftware.Extensions.Collections` package version to 1.1.2-alpha.6

- TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
This PR will introduce a new pre-release for the `TryAtSoftware.Extensions.Reflection` package.
> Increased the `TryAtSoftware.Extensions.Reflection` package version to 1.1.2-alpha.2

- .editorconfig
- .github/workflows/Core validation.yml
- .github/workflows/Publish packages.yml
- TryAtSoftware.Extensions.Collections.Tests/TryAtSoftware.Extensions.Collections.Tests.csproj
- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
- TryAtSoftware.Extensions.DependencyInjection.Standard.Tests/ServiceConfigurationAttributeTests.cs
- TryAtSoftware.Extensions.DependencyInjection.Standard.Tests/ServiceRegistrarTests.cs
- TryAtSoftware.Extensions.DependencyInjection.Standard.Tests/TryAtSoftware.Extensions.DependencyInjection.Standard.Tests.csproj
- TryAtSoftware.Extensions.DependencyInjection.Standard.md
- TryAtSoftware.Extensions.DependencyInjection.Standard/Attributes/ServiceConfigurationAttribute.cs
- TryAtSoftware.Extensions.DependencyInjection.Standard/ServiceRegistrar.cs
- TryAtSoftware.Extensions.DependencyInjection.Standard/TryAtSoftware.Extensions.DependencyInjection.Standard.csproj
- TryAtSoftware.Extensions.DependencyInjection.Tests/TryAtSoftware.Extensions.DependencyInjection.Tests.csproj
- TryAtSoftware.Extensions.DependencyInjection/TryAtSoftware.Extensions.DependencyInjection.csproj
- TryAtSoftware.Extensions.Reflection.Tests/TryAtSoftware.Extensions.Reflection.Tests.csproj
- TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
_[Provide a brief description of the changes introduced by this pull request.]_
_[Explain in details the reasoning behind these changes and provide any relevant context. This can include potential impact or any alternative solutions considered.]_
> Automatic registration of keyed services

- TryAtSoftware.Extensions.Collections.Tests/TryAtSoftware.Extensions.Collections.Tests.csproj
- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
This PR will introduce a new patch release for the `TryAtSoftware.Extensions.Collections` package.
> Increased the `TryAtSoftware.Extensions.Collections` package version to 1.1.2

- TryAtSoftware.Extensions.Reflection.md
- TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
This PR will introduce a new patch release for the `TryAtSoftware.Extensions.Reflection` package.
> Increased the `TryAtSoftware.Extensions.Reflection` package version to 1.1.2

- TryAtSoftware.Extensions.DependencyInjection/TryAtSoftware.Extensions.DependencyInjection.csproj
This PR will introduce a new patch release for the `TryAtSoftware.Extensions.DependencyInjection` package.
> Increased the `TryAtSoftware.Extensions.DependencyInjection` package version to 1.1.2

- TryAtSoftware.Extensions.DependencyInjection.Standard.Tests/TryAtSoftware.Extensions.DependencyInjection.Standard.Tests.csproj
- TryAtSoftware.Extensions.DependencyInjection.Standard/TryAtSoftware.Extensions.DependencyInjection.Standard.csproj
This PR will introduce a new patch release for the `TryAtSoftware.Extensions.DependencyInjection.Standard` package.
> Increased the `TryAtSoftware.Extensions.DependencyInjection.Standard` package version to 1.1.2

- TryAtSoftware.Extensions.Collections.Tests/TryAtSoftware.Extensions.Collections.Tests.csproj
- TryAtSoftware.Extensions.Collections/TryAtSoftware.Extensions.Collections.csproj
- TryAtSoftware.Extensions.DependencyInjection.Standard.Tests/TryAtSoftware.Extensions.DependencyInjection.Standard.Tests.csproj
- TryAtSoftware.Extensions.DependencyInjection.Standard/TryAtSoftware.Extensions.DependencyInjection.Standard.csproj
- TryAtSoftware.Extensions.DependencyInjection.Tests/TryAtSoftware.Extensions.DependencyInjection.Tests.csproj
- TryAtSoftware.Extensions.DependencyInjection/TryAtSoftware.Extensions.DependencyInjection.csproj
- TryAtSoftware.Extensions.Reflection.Tests/AssemblyExtensionsTests.cs
- TryAtSoftware.Extensions.Reflection.Tests/GenericExtensionsTests.cs
- TryAtSoftware.Extensions.Reflection.Tests/Options/LoadReferencedAssembliesOptionsTests.cs
- TryAtSoftware.Extensions.Reflection.Tests/TryAtSoftware.Extensions.Reflection.Tests.csproj
- TryAtSoftware.Extensions.Reflection/TryAtSoftware.Extensions.Reflection.csproj
This PR finalizes the replacement of `Moq` with `NSubstitute`.
It follows the latest decision we made about our mocking approach.
> Finalized the replacement of Moq with NSubstitute
